### ISSUE TITLE
inconsistent: IDL attribute vs ruby method vs content attribute

### ISSUE THREAD

**Issue by jarib** [watir/watir-webdriver#28]
We're currently not translating between these correctly. 

e.g.:

<pre>
  def accept_charset
    @element.attribute("accept_charset")
  end
</pre>

should really be:

<pre>
  def accept_charset
    @element.attribute("accept-charset")
  end
</pre>

There's way too many of these to maintain by hand, so hopefully we can find a way to extract it from the HTML spec.

**Comment by titusfortner** [comment]
@p0deje did #261 fix this issue?

**Comment by p0deje** [comment]
@titusfortner It would still be great to allow to handle content attributes as well, but I believe IDL is fine in 99% of cases and watir-webdriver has been using them for a long time already, so I'm closing this.
