### ISSUE TITLE
Firefox 35: Javascript errors on common browser interactions

### ISSUE THREAD

**Issue by seanrobbins** [watir/watir-webdriver#306]
Steps to Reproduce:

1. Install Firefox v35

2. Errors can be re-created with the following code:

require 'watir-webdriver'

b = Watir::Browser.new :firefox
b.goto "www.google.com"
t = b.text_field(:id => "gbqfq")

t.flash  #this will throw this error: Selenium::WebDriver::Error::JavascriptError: arguments[0] is undefined 
t.focus #this will throw this error: Selenium::WebDriver::Error::JavascriptError: arguments[0] is undefined

**Comment by jarib** [comment]
What version of selenium-webdriver is being used here? Looks like the version you're running isn't compatible with Firefox 35.

**Comment by seanrobbins** [comment]
I think I am testing the latest development version. I can recreate the error with this:

gem 'selenium-webdriver', '=2.45.0.dev2'
require 'watir-webdriver'

b = Watir::Browser.new :firefox
b.goto "www.google.com"
t = b.text_field(:id => "gbqfq")

**Comment by jarib** [comment]
Thanks. This isn't an issue in watir-webdriver, but in selenium-webdriver. I've reported it [here](https://code.google.com/p/selenium/issues/detail?id=8390).

**Comment by seanrobbins** [comment]
Thank you so much for your fast response on this issue.
