### ISSUE TITLE
$HIDE_IE = true doesn't work

### ISSUE THREAD

**Issue by sayakb** [watir/watir-webdriver#308]
I am using watir-webdriver 0.6.10 with ruby 2.0.0p247 and cucumber. Before I create the browser instance, I do this:
```
require 'watir-webdriver'

$HIDE_IE = true
@browser = Watir::Browser.new :ie
```
However, the internet explorer window still pops up. Any pointers?

**Comment by jarib** [comment]
Wherever you found `$HIDE_IE`, it's probably referring to [watir-classic](https://github.com/watir/watir-classic). AFAIK there's no way to hide IE (or any browser) with watir-webdriver.

**Comment by sayakb** [comment]
Is there a way I can start it minimized? Our company is adopting BDD and we are integrating our end to end tests with Hudson CI. I want to avoid popping up IE windows on the build server. And our application (which is a humongous website that was started 10 years back) doesn't seem to work at all with phantomjs.

**Comment by jarib** [comment]
There's no way to minimize the browser window through the WebDriver (or watir-webdriver) API directly. It may be possible through something like [RAutomation](https://github.com/jarmo/RAutomation). If it's a build server I don't really understand why it's a problem that IE windows are popping up though.

**Comment by sayakb** [comment]
Thanks, I'll look into RAutomation.
