### ISSUE TITLE
HTMLElementCollection doesn't use selector in array index operations

### ISSUE THREAD

**Issue by osteenbergen** [watir/watir-webdriver#309]
Element collection has some unexpected behaviour when you use array operations.

Example:
```ruby
require "watir-webdriver"
b = Watir::Browser.start 'google.com'
result = b.elements(:id => "DOES_NOT_EXIST_ON_THE_PAGE")
# <Watir::HTMLElementCollection:0x00000001fe7bc0 .... @selector={:id=>"does_not_exist"}>
result.length # 0
result.size # 0
result.find_all.size # 0
result[0].tag_name # html
result[1].tag_name # head
result.first.tag_name # html
```

Reading the code it seems to be this function in ```lib/watir-webdriver/collections/element_collection.rb```
```ruby
def [](idx)
    to_a[idx] || element_class.new(@parent, :index => idx)
end
```

The selector doesn't return anything and therefor the to_a[idx] is empty, so a new element_class is created. However instead of using both the parent and the selector it only uses the parent. This can't be a correct answer:
```html
<div> <!--parent-->
  <span></span> <!-- first index of parent -->
  <ul id="list"> <!--selector-->
    <li></li> <!--first-->
  </ul>
</div>
```

**Comment by p0deje** [comment]
Thanks for the report!
