### ISSUE TITLE
Need a way to simulate scrolling of mousewheel

### ISSUE THREAD

**Issue by Chuckv** [watir/watir-webdriver#315]
There are a number of jquery type controls that create a scrollbox of some sort.   Great example is on this page http://rocha.la/jQuery-slimScroll.  obviously normal scroll functions fail on these controls, which want to be driven by mouse scrolling, or dragging of their 'scrollbar'

emulating mouse wheel scrolling would be a good way to interact with such a control, but we don't currently have a way to do that.   I suggest one of a few alternatives

1) provide a 'scroll_mouse' or 'scroll_mouse_wheel' method that would accept a delta value (signed int)  and fire off the appropriate event along with the delta parameter.   Note this might be best because apparently not all browsers handle this the same way (see http://www.sitepoint.com/html5-javascript-mouse-wheel/ presuming it is still correct) so this would free the user from having to know what event to fire and what direction was indicated by positive/negative delta values

2) extend fire_event so it can take a parameter, which would allow it to be used with onmousewheel or DOMMousescroll.  (however all users would then need to know which event (and +/-) to use for which browser)

bit more background on why this is needed:
In terms of the example control, normal scroll functions don't work on these controls (no surprise there) and they only seem to respond to events.  onmousescroll over the window, or dragging the scrollbar.   The problem is that the first is not supported (we can't send a parameter indicating the wheel delta, because fire_event does not allow that)  and the second is not always viable depending on the nature of the control.

If the control has the scrollbar always visible, then you can use drag operations on that element, but if the scroll control is set to appear/dissapear based on mouseover, it's flakey as hell and not reliable. firing mouseover events does not seem reliable, and in experimenting with this I've had the control just go hidden and stay that way (ugh).  and if not visible, not draggable.

**Comment by p0deje** [comment]
I would say this should be implemented in [watir-scroll](https://github.com/p0deje/watir-scroll/), so can you reopen the issue there? However, I don't see myself implementing that soon, so patches are welcome (a bit of JavaScript with `driver.execute_async_script` should work) :)
