### ISSUE TITLE
TableRow#click doesn't fire events under IE

### ISSUE THREAD

**Issue by jarmo** [watir/watir-webdriver#32]
TableRow#click - fires the rows's onclick event

Fails under IE because #click triggers only TABLE's event. When clicking on TD instead, then TD's, TR's and TABLE's events are triggered as expected.

When performing same click on TR with Watir 1.6.5 then events for TR and TABLE are triggered as expected.

**Comment by p0deje** [comment]
So, 5 years later I think we can close this issue. In any case, since `#click` is just send to WebDriver, if this issue still exists it should be reported there.

@jarmo Are you fine with it?

**Comment by jarmo** [comment]
Yeah, cool! Closed.
