### ISSUE TITLE
Alert disappears after rescuing UnhandledAlertError

### ISSUE THREAD

**Issue by idanci** [watir/watir-webdriver#330]
Scenario:
1) clicking on a button which spawns an alert
2) `browser.alert.present? #=> true`
3) `browser.div(:id => "test").present? #=> raises UnhandledAlertError`
4) UnhandledAlertError rescued
5) `browser.alert.present? #=> false`
6) `browser.div(:id => "test").present? #=> false`

Is it a normal behavior?

**Comment by titusfortner** [comment]
I came across this issue last year - https://github.com/watir/watir-webdriver/issues/280#issuecomment-59587241

It *might be a bug in Firefox, but I didn't raise it as one, and worked around it in the code instead. Is there something it is keeping you from doing?

**Comment by idanci** [comment]
The problem is that the alert appears inside a loop which does a lot of things. There are additional calls to driver even after UnhandledAlertError was rescued, but when I want to investigate the text of the alert it's already gone.

**Comment by titusfortner** [comment]
You are right, Firefox does not make it easy to troubleshoot alerts. Chrome would be easier in this case. 
If you want to raise it as a Firefox Driver bug - https://code.google.com/p/selenium/issues/list

**Comment by idanci** [comment]
Thanks for the feedback.
