### ISSUE TITLE
.exists? very slow on Firefox, not on Chrome

### ISSUE THREAD

**Issue by duncan-bayne** [watir/watir-webdriver#335]
This code:

```
browser.label(text: 'foo').exists?
```

... takes around 28ms to execute when running tests against Chrome, and around 267ms against Firefox.  In both cases, the label is present and visible and `exists?` returns `true`.

This ads up to a very significant difference in execution time for a large suite.

Versions of things that I think might be relevant:

```
    selenium-webdriver (2.45.0)
      childprocess (~> 0.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0)

    watir-webdriver (0.7.0)
      selenium-webdriver (>= 2.45)

    ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
    Google Chrome 41.0.2272.118
    Mozilla Firefox 37.0.1

    Linux Mint 17 Qiana, 64-bit Cinammon
```

This issue seems to occur across a wide range of developer machines and our CI box, including various versions of OSX, Linux Mint, and Ubuntu.

**Comment by p0deje** [comment]
That's the issue in selenium-webdriver 2.45. It has already been fixed in selenium, but not yet released. So, you should either downgrade selenium-webdriver and watir-webdriver or wait for new release.

**Comment by p0deje** [comment]
You should also join #selenium on freenode and ask why haven't they released it yet :) cc @lukeis @barancev @AutomatedTester

**Comment by simonrussell** [comment]
Just (perhaps for my benefit only) to save people some time searching, this is the bug in Selenium: SeleniumHQ/selenium#383.
