### ISSUE TITLE
#element does not find all elements by text

### ISSUE THREAD

**Issue by akostadinov** [watir/watir-webdriver#336]
watir 0.7.0, firefox 37
I see a strange issue with finding elements. See my html page http://fpaste.org/214513/ (I really hope this is useful as a sample as I've not idea how to get a shorter reproducer)

Now this is a pry session:
```
> selector = {:text=>"Confirm"}
> button = @@b.element(selector)
=> #<Watir::HTMLElement:0x..fe601d1c0f411dfc located=false selector={:text=>"Confirm"}>
> button.html
=> "<td style=\"vertical-align: top;\" align=\"left\"><button aria-describedby=\"confirmation-message\" style=\"min-width:60px;\" tabindex=\"0\" class=\"gwt-Button default-button primary\" type=\"button\">Confirm</button></td>"

> button = @@b.button(selector) 
=> #<Watir::Button:0x717994e4ecd8d3bc located=false selector={:text=>"Confirm", :tag_name=>"button"}>
> button.html
=> "<button aria-describedby=\"confirmation-message\" style=\"min-width:60px;\" tabindex=\"0\" class=\"gwt-Button default-button primary\" type=\"button\">Confirm</button>"
```

Above can be seen that when using `#element` it finds only one elements but that's the table cell, not the button itself, so clicking it has no effect.
When using `#button` then everything is right. 

Expected behaviour though for me would be `#element` to find 2 elements - the cell and the button. I see in other occasions `#element` finding outer and inner elements and returning an `ElementCollection`. So it seems like a bug that in this case it only returns the outer element but not the inner one.

**Comment by titusfortner** [comment]
To start with #element should never return more than one element. To get an array of matching elements, you want:
```
@@b.elements(selector)
```
In general, you should avoid using #element directly in favor of the more specific type of element you want.

This does raise another issue with our xpath matching, though. @p0deje can you help me out with this one? The xpath watir generates for a generic element does indeed return more than one element as matching a particular text inside a table. I've only ever used css selectors for my tests so I'm not as familiar with xpath. Any idea why [this spec](https://github.com/watir/watirspec/pull/65) pulls up both the th & the tr elements with 
```
{xpath: ".//*[normalize-space()='March 2008']"} 
```
Any easy way to fix it?

**Comment by p0deje** [comment]
As @titusfortner said, you should use `#elements` instead - `#element` will return the first element which text equals "Confirm". That happens to be `<td>` in your case.

**Comment by akostadinov** [comment]
Thanks, I'll try if `#elements` behaves consistently.
But are you leaving `#element` broken to return multiple elements sometimes?

**Comment by p0deje** [comment]
@akostadinov No, `#element` always returns one element.

**Comment by akostadinov** [comment]
you are right, sorry for confusion
