### ISSUE TITLE
How to render webdriver events in iframe?

### ISSUE THREAD

**Issue by EMRJ** [watir/watir-webdriver#338]
I want to mimic the following functionality in real time using watir-webdriver, I want to attach watir-webdriver events to my existing tab, I analyzed about watir-classic but it's only for windows machines I am using ubuntu 14.04, firefox 

Is it possible to render webdriver events in already opened window?

Ref: http://3.bp.blogspot.com/-VhPbMbIjfME/VOte4du-sBI/AAAAAAAADIU/gE6xZERTFnU/s1600/Inbox3.gif

**Comment by titusfortner** [comment]
No, a webdriver implementation can only send commands to a browser that it has opened.
