### ISSUE TITLE
Add support for Ruby 1.9.3 back

### ISSUE THREAD

**Issue by abotalov** [watir/watir-webdriver#340]
* Up until recently (Feb 2015) RubyInstaller (probably, the most popular way to install Ruby on Windows) [recommended to use MRI 1.9.3](https://web.archive.org/web/20150206111346/http://rubyinstaller.org/downloads)
* Watir-Webdriver is a web application testing library so many users might use for testing web app against browsers on Windows
* [Cucumber on Windows doesn't support Ruby > 2.0](https://github.com/cucumber/cucumber/issues/830) so it doesn't quiet worth for users to upgrade for only one version

**Comment by titusfortner** [comment]
Support for Ruby 1.9.3 [ended on February 23](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/), so we are no longer supporting it, either. You can still use Cucumber 1.3 if you want to use a different version of Ruby, or you can use the Ruby version that Cucumber 2 supports. Either way, this isn't a reason for Watir to change the versions it supports.

**Comment by p0deje** [comment]
Watir should be properly working on Ruby 1.9, it's just no longer supported. Also, there is still no official watir-webdriver release which drops Ruby 1.8/1.9.

**Comment by abotalov** [comment]
Actually, current Watir's master doesn't work on Ruby 1.9.3 because of e.g. this - https://github.com/watir/watir-webdriver/blob/master/lib/watir-webdriver/window.rb#L14

I think usage of Ruby 2.0 special syntax doesn't provide huge enough benefits to break work of Watir with Ruby 1.9.3

**Comment by p0deje** [comment]
Right, I've forgotten about symbol array shorthands.

I guess we can revert them to simple arrays and it should work fine.

**Comment by p0deje** [comment]
@abotalov Could you check and see how it works now?
