### ISSUE TITLE
Impossible to close browser on script exit via signal (Ctrl+C)

### ISSUE THREAD

**Issue by maxigs** [watir/watir-webdriver#341]
I'm trying to build a little script that opens a browser on start and performs some tasks (opening sites) whenever it receives a task.

Everything works fine so far but i'm unable to close the browser reliably on exit of the script including via Signal (Interrupt, for example Ctr+C)

No matter what i tried so far i receive the error:

    /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)

And the browser stays open running "abandoned".
A normal browser.close works fine, just not when i put it to be executed at end/interrupt.

It seems almost as if the selenium driver dissapears before ruby starts executing the Signal.trap code when hitting Ctrl+C.
Putting it in at_exit did not make a difference also.

I even tried some of the things mentioned here https://github.com/watir/watir-webdriver/issues/137 without luck.

**Comment by p0deje** [comment]
Can you post script example to debug?

**Comment by maxigs** [comment]
here is the full script to debug:

```
#!/usr/bin/env ruby
require 'watir-webdriver'

$browser = Watir::Browser.new :chrome
$browser.goto('http://google.com')

# to keep it running
sleep 100

# this works fine
$browser.close

# this does not work, producing the error when triggered
Signal.trap("INT") do
  puts "signal trap" # this does not get called
  $browser.close
end

at_exit do
  puts "at exit" # this does not get called
  $browser.close
end
```

which produces this error:
```
/usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1445:in `begin_transport'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1402:in `transport_request'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1147:in `head'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/chrome/service.rb:63:in `block in stop'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/chrome/service.rb:59:in `stop'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/chrome/service.rb:53:in `block in start'
	from /usr/local/opt/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/platform.rb:134:in `block in exit_hook'
bin/waitrtest:21:in `sleep': Interrupt
	from bin/waitrtest:21:in `<main>'
```

Also no code in trap or at_exit is called.
I did also try evened code instead of a plain sleep (as for the test now), but with the same results.

**Comment by p0deje** [comment]
```ruby
#!/usr/bin/env ruby
require 'selenium-webdriver'

begin
  $browser = Selenium::WebDriver.for :firefox
  $browser.get('http://google.com')
  sleep 100
rescue Interrupt
  $browser.quit
end
```

This seems to work fine with Firefox, but not Chrome.

I believe this might be a bug in selenium-webdriver. Please, report it.

**Comment by p0deje** [comment]
Btw, your trap doesn't work because it's executed after the process dies. You should write on the very top of file to ensure it's handled.

**Comment by maxigs** [comment]
Of course, thats why it didn't execute the trap. Sorry, i guess i missed it with so many trying different versions of the code.

With firefox it seems to work no matter the explicit quit. Even without the rescue and quit the browser is closed whenever the script exits.
Also it works as Watir::Browser not just as Selenium::WebDriver.

Thanks for your help!

**Comment by p0deje** [comment]
After discussion with @jarib, you can achieve the same behavior with Chrome using something like this:


```ruby
driver = Selenium::WebDriver.for(:chrome, detach: false)
browser = Watir::Browser.new(driver)
```

**Comment by p0deje** [comment]
And, by the way, you don't need to trap SIGINT and close browser, it's already handled by selenium-webdriver.

**Comment by maxigs** [comment]
> And, by the way, you don't need to trap SIGINT and close browser, it's already handled by selenium-webdriver.

I only started trying to do that because of the issue with chrome not closing. Makes sense that by default it closes/cleans-up the browser instance.

Setting the driver to chrome with detach: false seems to do the job now.
It's working as it should in my script (handling multiple instances) and closes them nicely.

Thanks again!
