### ISSUE TITLE
public documentation error

### ISSUE THREAD

**Issue by karlosmid** [watir/watir-webdriver#346]
There is public documentation error. On page:
http://watirwebdriver.com/chrome/

line
`b = Watir::Browser.new :chrome, :profile => profile`
should be repleaced with
`b = Watir::Browser.new :chrome, :prefs => profile`

chromedriver from 2.12
chrome = Version 43.0.2357.81
OS X 10.10.3

**Comment by p0deje** [comment]
I have no idea where watirwebdriver.com is hosted.

@jkotests Do you know?

**Comment by jkotests** [comment]
@p0deje, it is hosted by Wordpress. I only have permissions to modify watir.com, not watirwebdriver.com. To update the page would require contacting Alister Scott or maybe @zeljkofilipin?

**Comment by zeljkofilipin** [comment]
@p0deje you are already an admin at https://watirwebdriver.wordpress.com/
@jkotests I have just added you to admins, you will have to accept the invitation.

Apologies for the late reply, I was traveling, still catching up on mail. Please ping me if you need help.

**Comment by jkotests** [comment]
Thanks @karlosmid. I have updated the page to use the ChromeDriver 2 structure for preferences.

**Comment by karlosmid** [comment]
@jkotests I am glad that I could help. Checked with:
selenium-webdriver 2.46.2
watir-webdriver 0.7.0
