### ISSUE TITLE
regular expression shorthand no longer works for element selectors

### ISSUE THREAD

**Issue by AlanLGuy** [watir/watir-webdriver#350]
prior to watir-webdriver 0.8.0
` @browser.div(id: /element-id_\d/) `
previously returned the first element matching that expression.
now however, regular expression shorthand seems to be searching on the exact string rather than the applicable pattern.
 ` Watir::Exception::UnknownObjectException: unable to locate element, using {:id=>/element-id_\d/, :tag_name=>"div"} `

using the 'longhand': 
` div(:my_element, id: /element-id_[0-9]/) `
works as expected

**Comment by p0deje** [comment]
Can you provide with test case to reproduce the problem?

**Comment by p0deje** [comment]
No response during 1 month. Closing.
