### ISSUE TITLE
run_checkers and alerts

### ISSUE THREAD

**Issue by titusfortner** [watir/watir-webdriver#351]
Theoretically clicking an alert should run the error checkers since it can result in a reloaded page. Current implementation of Alerts is independent of the Browser, so it can't easily be triggered. 

My code is currently doing this workaround, but it shouldn't need a separate method:

``` 
def click_with_alert
    Page.browser.without_checkers { click }
    Page.browser.alert.ok
    Page.browser.run_checkers
end
```

**Comment by p0deje** [comment]
Do you mean we should run checkers after `Alert#ok`? I guess it's pretty easy to implement.

**Comment by Blackbaud-TitusFortner** [comment]
We'd have to make a significant change to how we implement Alerts, but it shouldn't be too complicated. I'm just adding it to the list of things to do. :) I should be able to get to it later this summer.

**Comment by p0deje** [comment]
Guess we need to extract checkers to `Watir::Checkers` which implements `#run`, `#add`, etc. Then we can pass it to `Alert` constructor.

**Comment by p0deje** [comment]
In master now.
