### ISSUE TITLE
Browser.goto generates UnhandledAlertError on redirect confirmation dialogs

### ISSUE THREAD

**Issue by oeihiko** [watir/watir-webdriver#355]
I believe this is a bug with watir-webdriver, but at the very least it's the topic of multiple unanswered stackoverflow questions.

Sometimes pages popup alerts on redirect (like when you try to navigate from facebook.com with an unfinished message, an alert will popup asking if you're sure you want to redirect). When using Browser.goto to navigate away from a page that would generate such an alert, watir throws an UnhandledAlertError. The problem is that the alert does not display until after goto() is called, so it cannot be handled outside of goto().

**Comment by p0deje** [comment]
Watir should not handle such cases. One of the ways to handle such a problem is to:

```ruby
begin
  browser.goto 'my_page'
rescue UnhandledAlertError
  browser.alert.close
  browser.goto 'my_page'
end
```

In any case, this is not a bug, but rather a question. Please, post it in [google group](https://groups.google.com/forum/#!forum/watir-general).
