### ISSUE TITLE
Wrong behavior while accessing elements

### ISSUE THREAD

**Issue by anandchavan** [watir/watir-webdriver#356]
Steps to reproduce -
1. Launch irb console
2. start with following commands -
require 'watir-webdriver'
b= Watir::Browser.new
b.goto "file:///D:/TestHtml.html"
belement=b.b(:id, "bold_element")
belement.text
belement.class

All the commands work perfectly except "belement=b.b(:id, "bold_element")"

Expected -
Since the element was successfully located and I was able to use in future steps, I should get the located=true
Console output -
=> #<Watir::HTMLElement:0xe060732 located=true selector={:id=>"bold_element", :tag_name=>"b"}>

Actual -
Console Output -
=> #<Watir::HTMLElement:0xe060732 located=false selector={:id=>"bold_element", :tag_name=>"b"}>

Please see attached file:///D:/TestHtml.html and screenshot.jpg

![screenshot](https://cloud.githubusercontent.com/assets/10352719/8767882/60d9d54c-2e89-11e5-910b-89c88c35a470.png)

For following file, please download the file and change the extension to html

![testhtml](https://cloud.githubusercontent.com/assets/10352719/8767888/8b63eb72-2e89-11e5-92b5-354d2f701766.jpg)

**Comment by p0deje** [comment]
Because elements are lazy located, it shows `located=false` until you make any calls to element (e.g. `#text`).

Not a bug in any case.
