### ISSUE TITLE
Needed help for clicking on center of xpath element in watir web driver

### ISSUE THREAD

**Issue by vidyasagarpogiri** [watir/watir-webdriver#357]
Hi i want to click on the center of xpath element in watir web driver, how to do that please provide me with the necessary syntax or example. Appreciated for your valuable answer.

**Comment by anilreddy** [comment]
@vidyasagarpogiri This is not a help forum it is an issue tracker. 
First of all you question is not proper. xpath is a locator it is not an web element. It is used to identify an element in a page. do you mean how to click an element by using xpath? if yes you can use like this:

```ruby
# if it is a button then
browser.button(text: 'name of the button').click
# if it is a span
browser.span(xpath: "//span[text()='text inside the span']").click
```

For more information check this: [watir-webdriver](http://watirwebdriver.com/)

You can ask here:
[StackoverFlow](http://stackoverflow.com/questions/tagged/watir-webdriver)

**Comment by vidyasagarpogiri** [comment]
ok I'm new to this and i want to click on the centre of the xpath element , kindly tell me how to do that.

**Comment by anilreddy** [comment]
@vidyasagarpogiri I understand close this issue and i told you that xpath is a locator not an element to click. First understand what is an xpath why it is used.
