### ISSUE TITLE
Selenium::WebDriver::Error::UnknownError: Permission denied to access property "handleEvent"

### ISSUE THREAD

**Issue by narzero** [watir/watir-webdriver#359]
When trying to click on a link I get the following:

```
Selenium::WebDriver::Error::UnknownError: Permission denied to access property "handleEvent"
from [remote server] https://cdn.shopify.com/s/assets/admin-1281904798962f996c66cecd685ab47c.js:11:in `unknown'
```

Here's the code:
```
$browser.elements(css: "a.btn:nth-child(3)")[0].click
```

The funny thing is that when I try to do this manually with Pry, it works.
```
# Works
add_new_link_button = $browser.elements(css: "a.btn:nth-child(3)")[0]
add_new_link_button.click
```
I'm using ruby (2.2.2p95), watir (5.0.0), watir-webdriver (0.8.0), selenium (0.2.11), selenium-webdriver (2.47.1) and firefox (40.0.3).

**Comment by p0deje** [comment]
I think you might want to downgrade Firefox because 40 is not supported by selenium-webdriver. If it still persists and you can provide a test script to reproduce the bug, report it to https://github.com/SeleniumHQ/selenium issue tracker.

In any case, this it not a bug in watir-webdriver.
