### ISSUE TITLE
Stub external services or blacklist it

### ISSUE THREAD

**Issue by sergeygaychuk** [watir/watir-webdriver#365]
Hi guys. First of all, thank you for your great job! Sorry for my English :smile: 

I have trouble with my project. Test is very slow because of slow loading cloud.typography.com. I disable it in my application.html. My question: do you have some blacklists [like here](https://github.com/thoughtbot/capybara-webkit/issues/677) or other solution without put 'Rails.env.test?' code to any sources?
Thank you

**Comment by p0deje** [comment]
watir-webdriver doesn't provide blacklist URLs, but you can probably do that by using proxy which will blacklist specific URLs.

In any case, this is not a bug. Please, post questions on [watir-general](https://groups.google.com/forum/#!forum/watir-general) Google group.

**Comment by titusfortner** [comment]
This should work the same for Watir. http://elementalselenium.com/tips/66-blacklist
Feel free to ask on the mailing list if you have issues with it.

**Comment by sergeygaychuk** [comment]
@p0deje and @titusfortner Thank you!
