### ISSUE TITLE
Deprecations in 0.9.0 are a little severe

### ISSUE THREAD

**Issue by rgalanakis** [watir/watir-webdriver#376]
We just pulled in 0.9.0 with its `after_hooks` change. Nicer API, good work.

Except the `checkers` methods are spamming deprecation warnings every time they are called (which as you'd expect can be multiple times per test run). I like pulling in the latest versions of things, but it'd be a nicer experience for the user to be a bit gentler with the deprecations. Right now my choice is between changing my code to 0.9.0 (which means if there is a bug forcing a rollback to 0.8, I need to revert this commit as well), or pinning to 0.8.0 until I'm more confident in 0.9.0 (webdriver stuff is so finicky, in fact the recent 2.48.0 selenium webdriver update just hosed us for some reason). FWIW I pinned back to 0.8.0.

I think it'd be nice idea to either 1) warn about deprecations only the first time a method is called, or 2) release 0.9.1 or 2 in a few weeks, once 0.9.x has baked a little, and give it the current aggressive deprecation warnings.

Thanks and hope that didn't come off as entitled- just a (self-interested) suggestion that I and probably other users would really appreciate.

**Comment by titusfortner** [comment]
First, what issue are you having with 2.48?

Do I understand you correctly that your concern is with the cluttering of stdout with deprecation warnings?

**Comment by rgalanakis** [comment]
Not sure what the 2.48 problem is- it only fails on headless on our Ubuntu CI machine (FireFox, not sure about others). It's too difficult to debug remote headless webdriver specs so I don't even have enough info to file a bug report (beyond "telling something to click didn't actually click it" but I doubt that's universally true).

Yes, my stdout is cluttered with deprecation warnings.

**Comment by titusfortner** [comment]
You should only be seeing deprecation warnings when you are adding or removing checkers, which shouldn't be all that often. Regardless, warnings should always happen on every call that is made with a deprecated method until support for the deprecated method is removed. The goal is to get people to update their code (and this one in particular should be relatively simple).

Definitely ping me on the Selenium issue tracker if you figure out your Firefox problem.
