### ISSUE TITLE
incorrect permissions on watir-webdriver/locators/element_locator.rb in *nix

### ISSUE THREAD

**Issue by bensinober** [watir/watir-webdriver#381]
Hi,
the bundled gem 0.9.0 fails on load on my ubuntu 14.04 virtual box
```
[1] pry(main)> require 'watir-webdriver'
LoadError: cannot load such file -- watir-webdriver/locators/element_locator
from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
```
on further inspections, the file is unreadable by others than owner:

ls /var/lib/gems/2.2.0/gems/watir-webdriver-0.9.0/lib/watir-webdriver/locators/ -la
```
-rw-r--r-- 1 root root  2076 Oct 14 23:56 button_locator.rb
-rw-r--r-- 1 root root   590 Oct 14 23:56 child_cell_locator.rb
-rw-r--r-- 1 root root   810 Oct 14 23:56 child_row_locator.rb
-rw------- 1 root root 12171 Oct 14 23:56 element_locator.rb
-rw-r--r-- 1 root root   666 Oct 14 23:56 text_area_locator.rb
-rw-r--r-- 1 root root  2433 Oct 14 23:56 text_field_locator.rb
```
by changing the permissions (chmod +r) it worked

gem 0.8.0 does not have this problem

**Comment by titusfortner** [comment]
Weird, this is fine on my computer when I pull master, but I just unpacked the gem, and sure enough the permission issue is there. I don't know how that even happens.

This is also the same issue as #377

I'll do a point release from my machine to see if it fixes. In the meantime you can probably put in your gemfile:
```
gem 'watir-webdriver', :github => 'watir/watir-webdriver'
```

**Comment by titusfortner** [comment]
Before publishing 0.9.1 I built and unpacked the gem and the permissions looked good. 
@Kirikami & @bensinober please verify that it works as expected and I'll close this issue.

**Comment by p0deje** [comment]
I am also not sure how this happened, though I have 600 permissions on the file locally (that probably means I've pushed this permission in 0.9).

I've checked all other files - the permissions are fine there. Wonder if there is an automated wait to check them before release.

**Comment by Kirikami** [comment]
Looks like this bug solved, now I have problem with monkey patching but I'll resolve it later.
Thank you.

**Comment by p0deje** [comment]
@titusfortner Please, push the changes to master :)

**Comment by bensinober** [comment]
@titusfortner I can affirm that the issue is resolved. Thanks for this quick fix!

**Comment by titusfortner** [comment]
@p0deje - oops, wanted to verify the gem locally before publishing and I forgot to push to master after. Thanks. :)

@Kirikami - Let us know if you need anything regarding the monkey patching fix.
