### ISSUE TITLE
Open bracket in send_keys for select2 dropdown input results in option scroll down rather than text input

### ISSUE THREAD

**Issue by gavk34** [watir/watir-webdriver#382]
When entering an open bracket into a select2 drop down the next option is highlighted rather than inputting the open bracket
watir-webdriver (0.8.0)
selenium-webdriver (2.47.1)
Firefox (41.0.1)

![snip20151105_2](https://cloud.githubusercontent.com/assets/8747391/10974663/15d356ac-83db-11e5-9113-31159983fb13.png)

Sample Code
```
require 'watir-webdriver'
browser = Watir::Browser.new
browser.goto 'https://select2.github.io/examples.html'
browser.span(:class => 'select2-selection', :index => 1).when_present.click
browser.input(:class, 'select2-search__field').when_present.send_keys '('
```

**Comment by titusfortner** [comment]
You can track this issue in the Selenium project.
