### ISSUE TITLE
Command key modifier doesn't work on Mac OS

### ISSUE THREAD

**Issue by sumproxy** [watir/watir-webdriver#383]
send_keys [:command, 'f']
has no effect in watir-webdriver (0.9.1)

**Comment by p0deje** [comment]
Please, provide an example test case to reproduce the issue.

**Comment by sumproxy** [comment]
```ruby
require 'watir-webdriver'
b = Watir::Browser.new :chrome
b.send_keys [:command, 'h']
```
The browser window should be hidden, yet nothing happens. Command returns nil if run from irb

**Comment by p0deje** [comment]
I see that you have opened SeleniumHQ/selenium#1290, so I'm going to close this as not watir-webdriver issue.
