### ISSUE TITLE
Run webdriver on IOS devices

### ISSUE THREAD

**Issue by diffsavannah** [watir/watir-webdriver#385]
Hi there,
Is it possible to run webdriver on IOS devices?
We expect to make an iPhone app running webdriver to do web ui testing sort of jobs automatically after deploying the app to IOS devices. Therefore, we need:
1. either install webdriver on IOS somehow
2. or have webdriver as a standalone toolbox that still can be called in our ruby code and can also be packaged in our final app to run on IOS devices. 
We haven't seen such a functionality, so we want to check with you. 
Thank you.

**Comment by p0deje** [comment]
This is a question rather than a bug. Please post questions in [watir-general](https://groups.google.com/forum/#!forum/watir-general) Google group.
