### ISSUE TITLE
Cannot set correct value on input field of type number

### ISSUE THREAD

**Issue by dideler** [watir/watir-webdriver#391]
When not running headless, setting a value in an input field of type "number" does not work as expected. The value being entered gets a character cut off, for example if the value is 2000, the field gets the value 200.

![screenshot 2016-01-06 10 47 41](https://cloud.githubusercontent.com/assets/497458/12140855/f157087e-b462-11e5-8512-6f1ef2c7d23e.png)

```html
<input class="ng-pristine ng-invalid ng-invalid-required ng-valid-number ng-valid-min" id="transfer_in_amount" min="100" name="transfer_in[amount]" ng-disabled="formstatus" ng-model="transfer.amount" placeholder="£100 minimum" proxyvalidity="" required="required" type="number">
```

Setting the value like this:
```ruby
browser.text_field(id: 'transfer_in_amount').set(amount)
```

However, if I set the amount twice, it sets the correct value the second time.
```ruby
2.times { browser.text_field(id: 'transfer_in_amount').set(amount) }
```

Using Firefox 41.0.2 and watir-webdriver 0.9.1.

Related to #272

**Comment by titusfortner** [comment]
Firstly, please verify your version of selenium-webdriver gem.
Secondly, Selenium no longer supports Firefox 41 (currently 43, 42, 38 & 31)

Regardless, this is more likely to be a driver bug than a Watir bug. To verify, please run your test while adding ```$DEBUG = true``` before the offending line.
post what it puts to stdout so we can see exactly what is getting sent to the driver.

**Comment by dideler** [comment]
Using selenium-webdriver 2.48.1.

Upgrading to Firefox 43.0.4 made the issue disappear, thanks!
