### ISSUE TITLE
Chrome instructions on website have the wrong URL to the webdriver

### ISSUE THREAD

**Issue by FanaHOVA** [watir/watir-webdriver#404]
The link on [this](http://watirwebdriver.com/chrome/) page is no longer working. Correct link is [this](http://chromedriver.storage.googleapis.com/index.html) one.

**Comment by abaird** [comment]
@FanaHOVA - this should be fixed now, thanks for the info

**Comment by abaird** [comment]
@titusfortner - I would close this issue but I can't - is this something you can do?
