### ISSUE TITLE
Is it possible to control one remote session from two different remote browser instances?

### ISSUE THREAD

**Issue by idanci** [watir/watir-webdriver#407]
```ruby
browser1 = Watir::Browser.new(:remote, :url => "http://localhost:4444/wd/hub")
browser1.driver.session_id #=> "c86c614d-7424-4e65-b29d-960a716158ed"

browser2 = Watir::Browser.new(:remote, :url => "http://localhost:4444/wd/hub")
browser2.driver.session_id #=> "1c2fbcc5-97ea-4306-ad55-a9d1e955be66"
```

Is there any way to change `browser2`s session_id to control `browser1`?

There is no `session_id=` method for `browser.driver` so I wonder, do I have to monkey patch watir-webdriver or I have to play with selenium directly without my favorite webdriver?

**Comment by titusfortner** [comment]
No, you need to keep track of your browser1 variable. I'm guessing your use case is similar [to this one](https://github.com/SeleniumHQ/selenium/pull/1346), and it wont' be supported.

**Comment by idanci** [comment]
Thank you.
