### ISSUE TITLE
Failing to change window position

### ISSUE THREAD

**Issue by ch1c0t** [watir/watir-webdriver#418]
I got one spec failed:
```
  1) Window manipulating size and position should move the window                     
     Failure/Error: expect(new_pos.x).to eq initial_pos.x + 10
       
       expected: 970
            got: 960
       
       (compared using ==)
     # ./spec/watirspec/window_switching_spec.rb:380:in `block (5 levels) in <top (required)>'
```

It might have something to do with me using [i3](https://i3wm.org/). When I run `browser.window.move_to x, y`, no error arises, but the position stays the same.

**Comment by titusfortner** [comment]
Which browser & OS?

**Comment by ch1c0t** [comment]
```
➜  ~ firefox --version
Mozilla Firefox 45.0.1
➜  ~ uname -a
Linux zero 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux
```

**Comment by titusfortner** [comment]
It's working for me just fine in Linux Mint with Firefox 45. Have you tried running with settings that are more easily visible than 10 px? Have you made sure the browser has room to move the direction you are indicating? Note also that this functionality is not going to be supported in the w3c standard (and therefore not in Marionette).

**Comment by ch1c0t** [comment]
>Have you tried running with settings that are more easily visible than 10 px?

No. I just want to get all specs passed. But I'm pretty sure it wouldn't work either(see below why).

>Have you made sure the browser has room to move the direction you are indicating?

The browser has no room for it, because all its movements are supposed to be managed by [i3](https://i3wm.org/). 

Presumably, this issue can also be reproduced with other tiling window managers. Shouldn't `Watir::Window#move_to` raise something alike to `NotImplemented` error or return `nil` if the environment happens not to support moving?

**Comment by titusfortner** [comment]
All Watir is doing is using Selenium to communicate to a browser driver for the browser to take an action. If the window manager you are using prevents that action from taking place, perhaps it might be the driver's responsibility to recognize that and return an error to Selenium. If that were the case, it should be reported as an issue for that driver. Most of the energy for Firefox is going into making Marionette work, and Marionette will not be supporting this feature.

Regardless, I do not believe that Watir should do anything differently for this.
