### ISSUE TITLE
Build is failing at Travis

### ISSUE THREAD

**Issue by jarmo** [watir/watir-webdriver#427]
There is a failing build for two months at [Travis](https://travis-ci.org/watir/watir-webdriver).

**Comment by titusfortner** [comment]
That's a PR - this is the latest on master - https://travis-ci.org/watir/watir-webdriver/builds/119001452

**Comment by jarmo** [comment]
Right. Sorry about that :) Didn't expect Travis to show random pull request on its main view.

**Comment by titusfortner** [comment]
No worries, I agree it is weird. It took me a bit to realize it. I'm also frustrated I haven't gotten to look at the PR, too. Spending all my extra time with Selenium right now, and neglecting Watir. :(
