### ISSUE TITLE
Watir::Browser.new hangs on browser launch

### ISSUE THREAD

**Issue by soumyaray** [watir/watir-webdriver#429]
I love using Watir-webdriver!  I've used it extensively in the past, but now that I return to it, its not working.

In pry/irb, I try this:
```
require 'watir-webdriver'
browser = Watir::Browser.new
```

Firefox opens but my pry session is hung.  I can only exit the hang by `^C`, at which point I'm shown the following error:
```
^CInterrupt: 
from /Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/socket_poller.rb:114:in `sleep'
```

I've tried it with safari as well:
```
browser = Watir::Browser.new :safari
```

and get something similar.  Safari opens up a SafariDriver Launcher and shows (in browser:
```
SafariDriver Launcher

[  0.023s] [safaridriver.client] Connecting to SafariDriver browser extension...
[  0.035s] [safaridriver.client] This will fail if you have not installed the latest SafariDriver extension from
http://selenium-release.storage.googleapis.com/index.html
[  0.036s] [safaridriver.client] Extension logs may be viewed by clicking the Selenium [✓] button on the Safari toolbar
[  2.580s] [safaridriver.client] Unable to establish a connection with the SafariDriver extension
```

and i have to `^C` in pry to get out, or just wait for a timeout.

I'm using Ruby 2.3.1 and Watir-webdriver 0.9.1

Any ideas?

**Comment by titusfortner** [comment]
To use the latest Firefox version (47.0.1), please update your selenium-webdriver gem to 2.53.4
To use Safari, please make sure you have manually installed the SafariDriver extension.

**Comment by soumyaray** [comment]
thanks for the quick resolution!
