### ISSUE TITLE
Issue with Firefox 47.0.1

### ISSUE THREAD

**Issue by CJKinni** [watir/watir-webdriver#431]
I'm having issues with being unable to connect:

> lib/selenium/webdriver/firefox/launcher.rb:90:in `connect_until_stable': unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)

This is possibly related to https://github.com/SeleniumHQ/selenium/issues/2110

**Comment by titusfortner** [comment]
Please update your selenium-webdriver gem to 2.53.4 and make sure you are using Firefox 47.0.1
