### ISSUE TITLE
Receiving Locating Text Area Warning when attempting to utilize Text Field  

### ISSUE THREAD

**Issue by austinmarcum** [watir/watir-webdriver#434]
I am receiving the warning of "Locating textareas with '#text_field' is deprecated. Please, use '#textarea' method instead." (in text_field.rb line 35). I am attempting to use the text field on a input of with a class of text. The warning is thrown if the element type you are using (in this case, my attribute is "text") is not contained in the non text types list. I believe the negation should be taken off; that way if it is a non text type then throw the warning. 

Thank you for your time.

Austin Marcum

**Comment by titusfortner** [comment]
Ah yes, this code was changed in today's release. Thanks for reporting it, we'll take a look.

**Comment by titusfortner** [comment]
Fixed with #435 & released 0.9.3
